### ISSUE TITLE
execString()'s callback can not be called when run in child_process of node?

### ISSUE THREAD

**Issue by cz-Michael** [TooTallNate/node-applescript#4] opened 2014-06-12 21:58 UTC
I run execString("some applescript", function(){"printout"});
But the callback function doesn't work while the applescript has been execute! 
Can someone please give me a help?

**Comment by clarkieryan** [comment] 2016-03-10 10:12
Might be able to shed some light - a year on. Using a simple process.nextTick() loop causes a similar issue. 

`var loop = function(){
	//Exec here
	process.nextTick(loop);
};
process.nextTick(loop);`

**Comment by sonicdoe** [comment] 2018-06-12 07:14
@clarkieryan Do you mean something like the following?

```js
process.nextTick(() => {
  applescript.execString('tell application "iTunes" to get name of selection', (err, result) => {
    console.log(result)
  })
})
```

This works fine for me in Node.js v10 (and even Node.js v4).

Anyway, since another two years have passed, I’m going to close this. If anyone can still reproduce this issue, let me know and I’ll reopen.

**Closed by sonicdoe** 2018-06-12 07:14 UTC
